### ISSUE TITLE
Drop text to new paragraph

### ISSUE THREAD

**Issue by rstender** [hypenotic/ecoman#31]
Jonas wanted to see if we could align the Buy Now buttons of Curated Plants with Mineral Soil Mix.

Wonder if you could add a new paragraph in Curated plants and change this:

> A dozen locally-grown, hardy, low-maintenance plants excited to thrive on your balcony or terrace. (Be sure to grab a bag of Ecoman mineral soil mix).

To this:

> A dozen locally-grown, hardy, low-maintenance plants excited to thrive on your balcony or terrace. 
> 
> Be sure to grab a bag of Ecoman mineral-based soil mix, too.

**Comment by lionelmann** [comment]
closed
