### ISSUE TITLE
Image style in posts

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/ecoman#7]
I know sometimes Jonas won't have images that are ideal for narrow full width, but it would be great if we could force him to collect images going forward that were ideal for that.

Is the style for this set up in the backend, so he can upload pictures appropriate for full width to a field in the post?

![screen shot 2016-03-11 at 10 59 17 am](https://cloud.githubusercontent.com/assets/10924897/13707633/92b70ac8-e778-11e5-9ab0-de93bb76ee21.png)
![screen shot 2016-03-11 at 11 01 16 am](https://cloud.githubusercontent.com/assets/10924897/13707637/97cd9978-e778-11e5-96e3-9efe97e8e5b7.png)

**Comment by emdecr** [comment]
Yup! We've set up a short code, so he can make any image within a post full width.
_View when logged in_: http://ecoman.ca/?p=1680&preview_id=1680
_Shortcode_: [fullimage][/fullimage]
We also have a short code for inline tweets (also used in the test post): [tweet][/tweet]
![testpost](https://cloud.githubusercontent.com/assets/10912003/13857600/fbea7f84-ec50-11e5-97a0-b8a1b2d2e62d.jpg)
